# Generated by Django 5.1.5 on 2025-01-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название тайтла')),
                ('rate', models.IntegerField(default=0, verbose_name='Оценка')),
            ],
        ),
    ]
